server:
  port: 8080
spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true
  mvc:
    static-path-pattern: classpath:/templates/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  typeAliasesPackage: com.wuaipic.model
  mapperLocations: classpath:mapper/*.xml
---
server:
  port: 8081
# 设置session过期时间
#  servlet:
#    session:
#      timeout: 1m
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.73.177:3306/wuaipic?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0


---

server:
  port: 8082
spring:
  profiles: prod